namespace TesteConexão
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.btn_close = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbx_code = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbx_nome = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbx_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbx_tel = new Bunifu.UI.WinForms.BunifuTextBox();
            this.grdV_data = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btn_cad = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_alt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_exc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_listar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grdV_data)).BeginInit();
            this.SuspendLayout();
            // 
            // panel
            // 
            this.panel.BackColor = System.Drawing.Color.Transparent;
            this.panel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel.BackgroundImage")));
            this.panel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel.BorderRadius = 1;
            this.panel.Controls.Add(this.btn_close);
            this.panel.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel.GradientBottomLeft = System.Drawing.Color.DodgerBlue;
            this.panel.GradientBottomRight = System.Drawing.Color.SpringGreen;
            this.panel.GradientTopLeft = System.Drawing.Color.DarkBlue;
            this.panel.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.panel.Location = new System.Drawing.Point(0, 0);
            this.panel.Name = "panel";
            this.panel.Quality = 10;
            this.panel.Size = new System.Drawing.Size(620, 40);
            this.panel.TabIndex = 0;
            // 
            // btn_close
            // 
            this.btn_close.AllowAnimations = true;
            this.btn_close.AllowMouseEffects = true;
            this.btn_close.AllowToggling = false;
            this.btn_close.AnimationSpeed = 200;
            this.btn_close.AutoGenerateColors = false;
            this.btn_close.AutoRoundBorders = false;
            this.btn_close.AutoSizeLeftIcon = true;
            this.btn_close.AutoSizeRightIcon = true;
            this.btn_close.BackColor = System.Drawing.Color.Transparent;
            this.btn_close.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_close.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_close.BackgroundImage")));
            this.btn_close.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_close.ButtonText = "x";
            this.btn_close.ButtonTextMarginLeft = 0;
            this.btn_close.ColorContrastOnClick = 45;
            this.btn_close.ColorContrastOnHover = 45;
            this.btn_close.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_close.CustomizableEdges = borderEdges1;
            this.btn_close.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_close.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btn_close.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btn_close.DisabledForecolor = System.Drawing.Color.White;
            this.btn_close.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_close.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btn_close.ForeColor = System.Drawing.Color.White;
            this.btn_close.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_close.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_close.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_close.IconMarginLeft = 11;
            this.btn_close.IconPadding = 10;
            this.btn_close.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_close.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_close.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_close.IconSize = 25;
            this.btn_close.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btn_close.IdleBorderRadius = 1;
            this.btn_close.IdleBorderThickness = 1;
            this.btn_close.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_close.IdleIconLeftImage = null;
            this.btn_close.IdleIconRightImage = null;
            this.btn_close.IndicateFocus = false;
            this.btn_close.Location = new System.Drawing.Point(569, 0);
            this.btn_close.Name = "btn_close";
            this.btn_close.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_close.OnDisabledState.BorderRadius = 1;
            this.btn_close.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_close.OnDisabledState.BorderThickness = 1;
            this.btn_close.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btn_close.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btn_close.OnDisabledState.IconLeftImage = null;
            this.btn_close.OnDisabledState.IconRightImage = null;
            this.btn_close.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_close.onHoverState.BorderRadius = 1;
            this.btn_close.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_close.onHoverState.BorderThickness = 1;
            this.btn_close.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btn_close.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_close.onHoverState.IconLeftImage = null;
            this.btn_close.onHoverState.IconRightImage = null;
            this.btn_close.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_close.OnIdleState.BorderRadius = 1;
            this.btn_close.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_close.OnIdleState.BorderThickness = 1;
            this.btn_close.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn_close.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_close.OnIdleState.IconLeftImage = null;
            this.btn_close.OnIdleState.IconRightImage = null;
            this.btn_close.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btn_close.OnPressedState.BorderRadius = 1;
            this.btn_close.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_close.OnPressedState.BorderThickness = 1;
            this.btn_close.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn_close.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_close.OnPressedState.IconLeftImage = null;
            this.btn_close.OnPressedState.IconRightImage = null;
            this.btn_close.Size = new System.Drawing.Size(51, 40);
            this.btn_close.TabIndex = 0;
            this.btn_close.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_close.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_close.TextMarginLeft = 0;
            this.btn_close.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_close.UseDefaultRadiusAndThickness = true;
            this.btn_close.Click += new System.EventHandler(this.btn_close_Click);
            // 
            // tbx_code
            // 
            this.tbx_code.AcceptsReturn = false;
            this.tbx_code.AcceptsTab = false;
            this.tbx_code.AnimationSpeed = 200;
            this.tbx_code.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_code.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_code.BackColor = System.Drawing.Color.Transparent;
            this.tbx_code.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_code.BackgroundImage")));
            this.tbx_code.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_code.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_code.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_code.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.tbx_code.BorderRadius = 35;
            this.tbx_code.BorderThickness = 1;
            this.tbx_code.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_code.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_code.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbx_code.DefaultText = "";
            this.tbx_code.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            this.tbx_code.ForeColor = System.Drawing.Color.DodgerBlue;
            this.tbx_code.HideSelection = true;
            this.tbx_code.IconLeft = null;
            this.tbx_code.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_code.IconPadding = 10;
            this.tbx_code.IconRight = null;
            this.tbx_code.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_code.Lines = new string[0];
            this.tbx_code.Location = new System.Drawing.Point(28, 72);
            this.tbx_code.MaxLength = 32767;
            this.tbx_code.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_code.Modified = false;
            this.tbx_code.Multiline = false;
            this.tbx_code.Name = "tbx_code";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_code.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_code.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_code.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            stateProperties4.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_code.OnIdleState = stateProperties4;
            this.tbx_code.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_code.PasswordChar = '\0';
            this.tbx_code.PlaceholderForeColor = System.Drawing.Color.DodgerBlue;
            this.tbx_code.PlaceholderText = "Código";
            this.tbx_code.ReadOnly = false;
            this.tbx_code.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_code.SelectedText = "";
            this.tbx_code.SelectionLength = 0;
            this.tbx_code.SelectionStart = 0;
            this.tbx_code.ShortcutsEnabled = true;
            this.tbx_code.Size = new System.Drawing.Size(260, 37);
            this.tbx_code.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_code.TabIndex = 1;
            this.tbx_code.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_code.TextMarginBottom = 0;
            this.tbx_code.TextMarginLeft = 3;
            this.tbx_code.TextMarginTop = 0;
            this.tbx_code.TextPlaceholder = "Código";
            this.tbx_code.UseSystemPasswordChar = false;
            this.tbx_code.WordWrap = true;
            // 
            // tbx_nome
            // 
            this.tbx_nome.AcceptsReturn = false;
            this.tbx_nome.AcceptsTab = false;
            this.tbx_nome.AnimationSpeed = 200;
            this.tbx_nome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_nome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_nome.BackColor = System.Drawing.Color.Transparent;
            this.tbx_nome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_nome.BackgroundImage")));
            this.tbx_nome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_nome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_nome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_nome.BorderColorIdle = System.Drawing.Color.SpringGreen;
            this.tbx_nome.BorderRadius = 35;
            this.tbx_nome.BorderThickness = 1;
            this.tbx_nome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_nome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_nome.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbx_nome.DefaultText = "";
            this.tbx_nome.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            this.tbx_nome.ForeColor = System.Drawing.Color.SpringGreen;
            this.tbx_nome.HideSelection = true;
            this.tbx_nome.IconLeft = null;
            this.tbx_nome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_nome.IconPadding = 10;
            this.tbx_nome.IconRight = null;
            this.tbx_nome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_nome.Lines = new string[0];
            this.tbx_nome.Location = new System.Drawing.Point(328, 72);
            this.tbx_nome.MaxLength = 32767;
            this.tbx_nome.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_nome.Modified = false;
            this.tbx_nome.Multiline = false;
            this.tbx_nome.Name = "tbx_nome";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_nome.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_nome.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_nome.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.SpringGreen;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            stateProperties8.ForeColor = System.Drawing.Color.SpringGreen;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_nome.OnIdleState = stateProperties8;
            this.tbx_nome.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_nome.PasswordChar = '\0';
            this.tbx_nome.PlaceholderForeColor = System.Drawing.Color.SpringGreen;
            this.tbx_nome.PlaceholderText = "Nome";
            this.tbx_nome.ReadOnly = false;
            this.tbx_nome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_nome.SelectedText = "";
            this.tbx_nome.SelectionLength = 0;
            this.tbx_nome.SelectionStart = 0;
            this.tbx_nome.ShortcutsEnabled = true;
            this.tbx_nome.Size = new System.Drawing.Size(260, 37);
            this.tbx_nome.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_nome.TabIndex = 2;
            this.tbx_nome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_nome.TextMarginBottom = 0;
            this.tbx_nome.TextMarginLeft = 3;
            this.tbx_nome.TextMarginTop = 0;
            this.tbx_nome.TextPlaceholder = "Nome";
            this.tbx_nome.UseSystemPasswordChar = false;
            this.tbx_nome.WordWrap = true;
            // 
            // tbx_email
            // 
            this.tbx_email.AcceptsReturn = false;
            this.tbx_email.AcceptsTab = false;
            this.tbx_email.AnimationSpeed = 200;
            this.tbx_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_email.BackColor = System.Drawing.Color.Transparent;
            this.tbx_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_email.BackgroundImage")));
            this.tbx_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_email.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.tbx_email.BorderRadius = 35;
            this.tbx_email.BorderThickness = 1;
            this.tbx_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbx_email.DefaultText = "";
            this.tbx_email.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            this.tbx_email.ForeColor = System.Drawing.Color.DodgerBlue;
            this.tbx_email.HideSelection = true;
            this.tbx_email.IconLeft = null;
            this.tbx_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.IconPadding = 10;
            this.tbx_email.IconRight = null;
            this.tbx_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_email.Lines = new string[0];
            this.tbx_email.Location = new System.Drawing.Point(28, 147);
            this.tbx_email.MaxLength = 32767;
            this.tbx_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_email.Modified = false;
            this.tbx_email.Multiline = false;
            this.tbx_email.Name = "tbx_email";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_email.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            stateProperties12.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_email.OnIdleState = stateProperties12;
            this.tbx_email.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_email.PasswordChar = '\0';
            this.tbx_email.PlaceholderForeColor = System.Drawing.Color.DodgerBlue;
            this.tbx_email.PlaceholderText = "E-mail";
            this.tbx_email.ReadOnly = false;
            this.tbx_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_email.SelectedText = "";
            this.tbx_email.SelectionLength = 0;
            this.tbx_email.SelectionStart = 0;
            this.tbx_email.ShortcutsEnabled = true;
            this.tbx_email.Size = new System.Drawing.Size(260, 37);
            this.tbx_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_email.TabIndex = 3;
            this.tbx_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_email.TextMarginBottom = 0;
            this.tbx_email.TextMarginLeft = 3;
            this.tbx_email.TextMarginTop = 0;
            this.tbx_email.TextPlaceholder = "E-mail";
            this.tbx_email.UseSystemPasswordChar = false;
            this.tbx_email.WordWrap = true;
            // 
            // tbx_tel
            // 
            this.tbx_tel.AcceptsReturn = false;
            this.tbx_tel.AcceptsTab = false;
            this.tbx_tel.AnimationSpeed = 200;
            this.tbx_tel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbx_tel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbx_tel.BackColor = System.Drawing.Color.Transparent;
            this.tbx_tel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbx_tel.BackgroundImage")));
            this.tbx_tel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbx_tel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbx_tel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbx_tel.BorderColorIdle = System.Drawing.Color.SpringGreen;
            this.tbx_tel.BorderRadius = 35;
            this.tbx_tel.BorderThickness = 1;
            this.tbx_tel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbx_tel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_tel.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbx_tel.DefaultText = "";
            this.tbx_tel.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            this.tbx_tel.ForeColor = System.Drawing.Color.SpringGreen;
            this.tbx_tel.HideSelection = true;
            this.tbx_tel.IconLeft = null;
            this.tbx_tel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_tel.IconPadding = 10;
            this.tbx_tel.IconRight = null;
            this.tbx_tel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbx_tel.Lines = new string[0];
            this.tbx_tel.Location = new System.Drawing.Point(328, 147);
            this.tbx_tel.MaxLength = 32767;
            this.tbx_tel.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbx_tel.Modified = false;
            this.tbx_tel.Multiline = false;
            this.tbx_tel.Name = "tbx_tel";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_tel.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbx_tel.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_tel.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.SpringGreen;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            stateProperties16.ForeColor = System.Drawing.Color.SpringGreen;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbx_tel.OnIdleState = stateProperties16;
            this.tbx_tel.Padding = new System.Windows.Forms.Padding(3);
            this.tbx_tel.PasswordChar = '\0';
            this.tbx_tel.PlaceholderForeColor = System.Drawing.Color.SpringGreen;
            this.tbx_tel.PlaceholderText = "Telefone";
            this.tbx_tel.ReadOnly = false;
            this.tbx_tel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbx_tel.SelectedText = "";
            this.tbx_tel.SelectionLength = 0;
            this.tbx_tel.SelectionStart = 0;
            this.tbx_tel.ShortcutsEnabled = true;
            this.tbx_tel.Size = new System.Drawing.Size(260, 37);
            this.tbx_tel.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbx_tel.TabIndex = 4;
            this.tbx_tel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbx_tel.TextMarginBottom = 0;
            this.tbx_tel.TextMarginLeft = 3;
            this.tbx_tel.TextMarginTop = 0;
            this.tbx_tel.TextPlaceholder = "Telefone";
            this.tbx_tel.UseSystemPasswordChar = false;
            this.tbx_tel.WordWrap = true;
            // 
            // grdV_data
            // 
            this.grdV_data.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.grdV_data.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.grdV_data.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.grdV_data.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.grdV_data.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.grdV_data.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.grdV_data.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.grdV_data.ColumnHeadersHeight = 40;
            this.grdV_data.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(227)))), ((int)(((byte)(255)))));
            this.grdV_data.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.grdV_data.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grdV_data.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            this.grdV_data.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.grdV_data.CurrentTheme.BackColor = System.Drawing.Color.DodgerBlue;
            this.grdV_data.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.grdV_data.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.grdV_data.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.grdV_data.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.grdV_data.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.grdV_data.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.grdV_data.CurrentTheme.Name = null;
            this.grdV_data.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.grdV_data.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.grdV_data.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.grdV_data.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            this.grdV_data.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(188)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.grdV_data.DefaultCellStyle = dataGridViewCellStyle3;
            this.grdV_data.EnableHeadersVisualStyles = false;
            this.grdV_data.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(187)))), ((int)(((byte)(221)))), ((int)(((byte)(255)))));
            this.grdV_data.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.grdV_data.HeaderBgColor = System.Drawing.Color.Empty;
            this.grdV_data.HeaderForeColor = System.Drawing.Color.White;
            this.grdV_data.Location = new System.Drawing.Point(28, 211);
            this.grdV_data.Name = "grdV_data";
            this.grdV_data.RowHeadersVisible = false;
            this.grdV_data.RowTemplate.Height = 40;
            this.grdV_data.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grdV_data.Size = new System.Drawing.Size(560, 214);
            this.grdV_data.TabIndex = 5;
            this.grdV_data.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DodgerBlue;
            this.grdV_data.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.grdV_data_CellClick);
            // 
            // btn_cad
            // 
            this.btn_cad.AllowAnimations = true;
            this.btn_cad.AllowMouseEffects = true;
            this.btn_cad.AllowToggling = false;
            this.btn_cad.AnimationSpeed = 200;
            this.btn_cad.AutoGenerateColors = false;
            this.btn_cad.AutoRoundBorders = false;
            this.btn_cad.AutoSizeLeftIcon = true;
            this.btn_cad.AutoSizeRightIcon = true;
            this.btn_cad.BackColor = System.Drawing.Color.Transparent;
            this.btn_cad.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_cad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_cad.BackgroundImage")));
            this.btn_cad.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cad.ButtonText = "CADASTRAR";
            this.btn_cad.ButtonTextMarginLeft = 0;
            this.btn_cad.ColorContrastOnClick = 45;
            this.btn_cad.ColorContrastOnHover = 45;
            this.btn_cad.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_cad.CustomizableEdges = borderEdges2;
            this.btn_cad.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_cad.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cad.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cad.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cad.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_cad.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btn_cad.ForeColor = System.Drawing.Color.White;
            this.btn_cad.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_cad.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cad.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_cad.IconMarginLeft = 11;
            this.btn_cad.IconPadding = 10;
            this.btn_cad.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_cad.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_cad.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_cad.IconSize = 25;
            this.btn_cad.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_cad.IdleBorderRadius = 35;
            this.btn_cad.IdleBorderThickness = 1;
            this.btn_cad.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_cad.IdleIconLeftImage = null;
            this.btn_cad.IdleIconRightImage = null;
            this.btn_cad.IndicateFocus = false;
            this.btn_cad.Location = new System.Drawing.Point(40, 442);
            this.btn_cad.Name = "btn_cad";
            this.btn_cad.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_cad.OnDisabledState.BorderRadius = 35;
            this.btn_cad.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cad.OnDisabledState.BorderThickness = 1;
            this.btn_cad.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cad.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cad.OnDisabledState.IconLeftImage = null;
            this.btn_cad.OnDisabledState.IconRightImage = null;
            this.btn_cad.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_cad.onHoverState.BorderRadius = 35;
            this.btn_cad.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cad.onHoverState.BorderThickness = 1;
            this.btn_cad.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_cad.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_cad.onHoverState.IconLeftImage = null;
            this.btn_cad.onHoverState.IconRightImage = null;
            this.btn_cad.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_cad.OnIdleState.BorderRadius = 35;
            this.btn_cad.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cad.OnIdleState.BorderThickness = 1;
            this.btn_cad.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_cad.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_cad.OnIdleState.IconLeftImage = null;
            this.btn_cad.OnIdleState.IconRightImage = null;
            this.btn_cad.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_cad.OnPressedState.BorderRadius = 35;
            this.btn_cad.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cad.OnPressedState.BorderThickness = 1;
            this.btn_cad.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_cad.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_cad.OnPressedState.IconLeftImage = null;
            this.btn_cad.OnPressedState.IconRightImage = null;
            this.btn_cad.Size = new System.Drawing.Size(114, 39);
            this.btn_cad.TabIndex = 8;
            this.btn_cad.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_cad.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_cad.TextMarginLeft = 0;
            this.btn_cad.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_cad.UseDefaultRadiusAndThickness = true;
            this.btn_cad.Click += new System.EventHandler(this.btn_cad_Click);
            // 
            // btn_alt
            // 
            this.btn_alt.AllowAnimations = true;
            this.btn_alt.AllowMouseEffects = true;
            this.btn_alt.AllowToggling = false;
            this.btn_alt.AnimationSpeed = 200;
            this.btn_alt.AutoGenerateColors = false;
            this.btn_alt.AutoRoundBorders = false;
            this.btn_alt.AutoSizeLeftIcon = true;
            this.btn_alt.AutoSizeRightIcon = true;
            this.btn_alt.BackColor = System.Drawing.Color.Transparent;
            this.btn_alt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_alt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_alt.BackgroundImage")));
            this.btn_alt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_alt.ButtonText = "ALTERAR";
            this.btn_alt.ButtonTextMarginLeft = 0;
            this.btn_alt.ColorContrastOnClick = 45;
            this.btn_alt.ColorContrastOnHover = 45;
            this.btn_alt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_alt.CustomizableEdges = borderEdges3;
            this.btn_alt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_alt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_alt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_alt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_alt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_alt.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btn_alt.ForeColor = System.Drawing.Color.White;
            this.btn_alt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_alt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_alt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_alt.IconMarginLeft = 11;
            this.btn_alt.IconPadding = 10;
            this.btn_alt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_alt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_alt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_alt.IconSize = 25;
            this.btn_alt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_alt.IdleBorderRadius = 35;
            this.btn_alt.IdleBorderThickness = 1;
            this.btn_alt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_alt.IdleIconLeftImage = null;
            this.btn_alt.IdleIconRightImage = null;
            this.btn_alt.IndicateFocus = false;
            this.btn_alt.Location = new System.Drawing.Point(176, 442);
            this.btn_alt.Name = "btn_alt";
            this.btn_alt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_alt.OnDisabledState.BorderRadius = 35;
            this.btn_alt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_alt.OnDisabledState.BorderThickness = 1;
            this.btn_alt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_alt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_alt.OnDisabledState.IconLeftImage = null;
            this.btn_alt.OnDisabledState.IconRightImage = null;
            this.btn_alt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_alt.onHoverState.BorderRadius = 35;
            this.btn_alt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_alt.onHoverState.BorderThickness = 1;
            this.btn_alt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_alt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_alt.onHoverState.IconLeftImage = null;
            this.btn_alt.onHoverState.IconRightImage = null;
            this.btn_alt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_alt.OnIdleState.BorderRadius = 35;
            this.btn_alt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_alt.OnIdleState.BorderThickness = 1;
            this.btn_alt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_alt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_alt.OnIdleState.IconLeftImage = null;
            this.btn_alt.OnIdleState.IconRightImage = null;
            this.btn_alt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_alt.OnPressedState.BorderRadius = 35;
            this.btn_alt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_alt.OnPressedState.BorderThickness = 1;
            this.btn_alt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_alt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_alt.OnPressedState.IconLeftImage = null;
            this.btn_alt.OnPressedState.IconRightImage = null;
            this.btn_alt.Size = new System.Drawing.Size(114, 39);
            this.btn_alt.TabIndex = 9;
            this.btn_alt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_alt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_alt.TextMarginLeft = 0;
            this.btn_alt.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_alt.UseDefaultRadiusAndThickness = true;
            this.btn_alt.Click += new System.EventHandler(this.btn_alt_Click);
            // 
            // btn_exc
            // 
            this.btn_exc.AllowAnimations = true;
            this.btn_exc.AllowMouseEffects = true;
            this.btn_exc.AllowToggling = false;
            this.btn_exc.AnimationSpeed = 200;
            this.btn_exc.AutoGenerateColors = false;
            this.btn_exc.AutoRoundBorders = false;
            this.btn_exc.AutoSizeLeftIcon = true;
            this.btn_exc.AutoSizeRightIcon = true;
            this.btn_exc.BackColor = System.Drawing.Color.Transparent;
            this.btn_exc.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_exc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_exc.BackgroundImage")));
            this.btn_exc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_exc.ButtonText = "EXCLUIR";
            this.btn_exc.ButtonTextMarginLeft = 0;
            this.btn_exc.ColorContrastOnClick = 45;
            this.btn_exc.ColorContrastOnHover = 45;
            this.btn_exc.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_exc.CustomizableEdges = borderEdges4;
            this.btn_exc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_exc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_exc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_exc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_exc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_exc.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btn_exc.ForeColor = System.Drawing.Color.White;
            this.btn_exc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_exc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_exc.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_exc.IconMarginLeft = 11;
            this.btn_exc.IconPadding = 10;
            this.btn_exc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_exc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_exc.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_exc.IconSize = 25;
            this.btn_exc.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_exc.IdleBorderRadius = 35;
            this.btn_exc.IdleBorderThickness = 1;
            this.btn_exc.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_exc.IdleIconLeftImage = null;
            this.btn_exc.IdleIconRightImage = null;
            this.btn_exc.IndicateFocus = false;
            this.btn_exc.Location = new System.Drawing.Point(313, 442);
            this.btn_exc.Name = "btn_exc";
            this.btn_exc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_exc.OnDisabledState.BorderRadius = 35;
            this.btn_exc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_exc.OnDisabledState.BorderThickness = 1;
            this.btn_exc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_exc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_exc.OnDisabledState.IconLeftImage = null;
            this.btn_exc.OnDisabledState.IconRightImage = null;
            this.btn_exc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_exc.onHoverState.BorderRadius = 35;
            this.btn_exc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_exc.onHoverState.BorderThickness = 1;
            this.btn_exc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_exc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_exc.onHoverState.IconLeftImage = null;
            this.btn_exc.onHoverState.IconRightImage = null;
            this.btn_exc.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_exc.OnIdleState.BorderRadius = 35;
            this.btn_exc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_exc.OnIdleState.BorderThickness = 1;
            this.btn_exc.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_exc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_exc.OnIdleState.IconLeftImage = null;
            this.btn_exc.OnIdleState.IconRightImage = null;
            this.btn_exc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_exc.OnPressedState.BorderRadius = 35;
            this.btn_exc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_exc.OnPressedState.BorderThickness = 1;
            this.btn_exc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_exc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_exc.OnPressedState.IconLeftImage = null;
            this.btn_exc.OnPressedState.IconRightImage = null;
            this.btn_exc.Size = new System.Drawing.Size(114, 39);
            this.btn_exc.TabIndex = 10;
            this.btn_exc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_exc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_exc.TextMarginLeft = 0;
            this.btn_exc.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_exc.UseDefaultRadiusAndThickness = true;
            this.btn_exc.Click += new System.EventHandler(this.btn_exc_Click);
            // 
            // btn_listar
            // 
            this.btn_listar.AllowAnimations = true;
            this.btn_listar.AllowMouseEffects = true;
            this.btn_listar.AllowToggling = false;
            this.btn_listar.AnimationSpeed = 200;
            this.btn_listar.AutoGenerateColors = false;
            this.btn_listar.AutoRoundBorders = false;
            this.btn_listar.AutoSizeLeftIcon = true;
            this.btn_listar.AutoSizeRightIcon = true;
            this.btn_listar.BackColor = System.Drawing.Color.Transparent;
            this.btn_listar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_listar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_listar.BackgroundImage")));
            this.btn_listar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_listar.ButtonText = "LISTAR";
            this.btn_listar.ButtonTextMarginLeft = 0;
            this.btn_listar.ColorContrastOnClick = 45;
            this.btn_listar.ColorContrastOnHover = 45;
            this.btn_listar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_listar.CustomizableEdges = borderEdges5;
            this.btn_listar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_listar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_listar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_listar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_listar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_listar.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btn_listar.ForeColor = System.Drawing.Color.White;
            this.btn_listar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_listar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_listar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_listar.IconMarginLeft = 11;
            this.btn_listar.IconPadding = 10;
            this.btn_listar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_listar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_listar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_listar.IconSize = 25;
            this.btn_listar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_listar.IdleBorderRadius = 35;
            this.btn_listar.IdleBorderThickness = 1;
            this.btn_listar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_listar.IdleIconLeftImage = null;
            this.btn_listar.IdleIconRightImage = null;
            this.btn_listar.IndicateFocus = false;
            this.btn_listar.Location = new System.Drawing.Point(454, 442);
            this.btn_listar.Name = "btn_listar";
            this.btn_listar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_listar.OnDisabledState.BorderRadius = 35;
            this.btn_listar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_listar.OnDisabledState.BorderThickness = 1;
            this.btn_listar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_listar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_listar.OnDisabledState.IconLeftImage = null;
            this.btn_listar.OnDisabledState.IconRightImage = null;
            this.btn_listar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_listar.onHoverState.BorderRadius = 35;
            this.btn_listar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_listar.onHoverState.BorderThickness = 1;
            this.btn_listar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_listar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_listar.onHoverState.IconLeftImage = null;
            this.btn_listar.onHoverState.IconRightImage = null;
            this.btn_listar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_listar.OnIdleState.BorderRadius = 35;
            this.btn_listar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_listar.OnIdleState.BorderThickness = 1;
            this.btn_listar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_listar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_listar.OnIdleState.IconLeftImage = null;
            this.btn_listar.OnIdleState.IconRightImage = null;
            this.btn_listar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_listar.OnPressedState.BorderRadius = 35;
            this.btn_listar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_listar.OnPressedState.BorderThickness = 1;
            this.btn_listar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_listar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_listar.OnPressedState.IconLeftImage = null;
            this.btn_listar.OnPressedState.IconRightImage = null;
            this.btn_listar.Size = new System.Drawing.Size(114, 39);
            this.btn_listar.TabIndex = 11;
            this.btn_listar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_listar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_listar.TextMarginLeft = 0;
            this.btn_listar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_listar.UseDefaultRadiusAndThickness = true;
            this.btn_listar.Click += new System.EventHandler(this.btn_listar_Click);
            // 
            // bunifuFormDock
            // 
            this.bunifuFormDock.AllowFormDragging = true;
            this.bunifuFormDock.AllowFormDropShadow = true;
            this.bunifuFormDock.AllowFormResizing = true;
            this.bunifuFormDock.AllowHidingBottomRegion = true;
            this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock.ContainerControl = this;
            this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock.DockingOptions.DockAll = true;
            this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock.DockingOptions.DockLeft = true;
            this.bunifuFormDock.DockingOptions.DockRight = true;
            this.bunifuFormDock.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock.DockingOptions.DockTopRight = true;
            this.bunifuFormDock.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock.ParentForm = this;
            this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = true;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(24)))), ((int)(((byte)(48)))));
            this.ClientSize = new System.Drawing.Size(620, 493);
            this.Controls.Add(this.btn_listar);
            this.Controls.Add(this.btn_exc);
            this.Controls.Add(this.btn_alt);
            this.Controls.Add(this.btn_cad);
            this.Controls.Add(this.grdV_data);
            this.Controls.Add(this.tbx_tel);
            this.Controls.Add(this.tbx_email);
            this.Controls.Add(this.tbx_nome);
            this.Controls.Add(this.tbx_code);
            this.Controls.Add(this.panel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form2";
            this.Text = "Form2";
            this.panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grdV_data)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel panel;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_code;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_nome;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_email;
        private Bunifu.UI.WinForms.BunifuTextBox tbx_tel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_close;
        private Bunifu.UI.WinForms.BunifuDataGridView grdV_data;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_cad;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_alt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_exc;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_listar;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
    }
}